[tool.poetry]
name = "lot1"
version = "0.1.0"
description = ""
authors = ["I-Teco"]

[tool.poetry.dependencies]
python = "3.7"
pyspark = "^3.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
